### ISSUE TITLE
Region save fail caused by IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by ahnl** [pl3xgaming/Pl3xMap#107]
My console is getting constantly flooded with these error logs:

```
[17:33:37 ERROR]: [Pl3xMap] Could not save map for region 0,0
[17:33:37 WARN]: javax.imageio.IIOException: Caught exception during read: 
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1847)
[17:33:37 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
[17:33:37 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
[17:33:37 WARN]:        at Pl3xMap-1.0.0-BETA-162.jar//net.pl3x.map.plugin.data.Image.save(Image.java:57)
[17:33:37 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[17:33:37 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:33:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:33:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:33:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:33:37 WARN]: Caused by: java.lang.IndexOutOfBoundsException
[17:33:37 WARN]:        at java.base/java.io.RandomAccessFile.readBytes(Native Method)
[17:33:37 WARN]:        at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:404)
[17:33:37 WARN]:        at java.desktop/javax.imageio.stream.FileImageInputStream.read(FileImageInputStream.java:117)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.common.SubImageInputStream.read(SubImageInputStream.java:61)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.common.InputStreamAdapter.read(InputStreamAdapter.java:47)
[17:33:37 WARN]:        at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:198)
[17:33:37 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:242)
[17:33:37 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[17:33:37 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[17:33:37 WARN]:        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
[17:33:37 WARN]:        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[17:33:37 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1245)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1381)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1514)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1840)
[17:33:37 WARN]:        ... 8 more
[17:33:37 ERROR]: [Pl3xMap] Could not save map for region 0,1
[17:33:37 WARN]: javax.imageio.IIOException: Caught exception during read: 
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1847)
[17:33:37 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
[17:33:37 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
[17:33:37 WARN]:        at Pl3xMap-1.0.0-BETA-162.jar//net.pl3x.map.plugin.data.Image.save(Image.java:57)
[17:33:37 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[17:33:37 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:33:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:33:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:33:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:33:37 WARN]: Caused by: java.lang.IndexOutOfBoundsException
[17:33:37 WARN]:        at java.base/java.io.RandomAccessFile.readBytes(Native Method)
[17:33:37 WARN]:        at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:404)
[17:33:37 WARN]:        at java.desktop/javax.imageio.stream.FileImageInputStream.read(FileImageInputStream.java:117)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.common.SubImageInputStream.read(SubImageInputStream.java:61)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.common.InputStreamAdapter.read(InputStreamAdapter.java:47)
[17:33:37 WARN]:        at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:198)
[17:33:37 WARN]:        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:242)
[17:33:37 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[17:33:37 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
[17:33:37 WARN]:        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
[17:33:37 WARN]:        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[17:33:37 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1245)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1381)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1514)
[17:33:37 WARN]:        at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1840)
[17:33:37 WARN]:        ... 8 more
```

Only regions 0,0 and 0,1 invoke the error.

<details>
<summary>The area has lots of mobs, could that possibly be the causation of the problem?</summary>

![image](https://user-images.githubusercontent.com/46541386/140653714-50dc3f74-2461-40d6-bd0c-7ec124260d02.png)

</details>

**Comment by ChristopherHaws** [comment]
I am also having this issue and there are no mobs in the chunks.

**Comment by BillyGalbreath** [comment]
Duplicate #45
