### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Schmensch** [pl3xgaming/Pl3xMap#108]
I tried to use this plugin on a Docker Paper Server, but it keeps giving me an error: Invalid Plugin.yml

Here's the full log:

```log
[18:18:57 ERROR]: Could not load 'plugins/86939.jar' in folder 'plugins'
 org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.1.jar:git-Paper-384]
 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[patched_1.17.1.jar:git-Paper-384]
 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-384]
 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-384]
 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-384]
 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-384]
```

**Comment by BillyGalbreath** [comment]
The plugin.yml is fine. Not sure what to tell you. Talk with whoever provided you the jar, as they've probably changed something incorrectly.

**Comment by Schmensch** [comment]
It was from Spigot.

**Comment by Schmensch** [comment]
It might be an issue on my side, I'm going to try a server with nothing except Pl3xmap

**Comment by Schmensch** [comment]
Nope, still the same error

**Comment by Schmensch** [comment]
Ok, apparently I can't read, and tried to install LiveAtlas (Dynmap / Pl3xmap frontend) as a Jar. Of course this can't work, and isn't Pl3xmap-related at all. I'm very sorry for wasting your time, hopfully I can get it working now with the actual Pl3xmap jar.
