### ISSUE TITLE
IllegalArgumentException or ExceptionInInitializerError on startup

### ISSUE THREAD

**Issue by Puremin0rez** [pl3xgaming/Pl3xMap#4]
```java
[19:25:04] [Server thread/INFO]: [Pl3xMap] Enabling Pl3xMap v1.0
[19:25:04] [Server thread/ERROR]: Error occurred while enabling Pl3xMap v1.0 (Is it up to date?)
java.lang.IllegalArgumentException: null
	at jdk.nio.zipfs.ZipPath.relativize(ZipPath.java:230) ~[jdk.zipfs:?]
	at net.pl3x.map.util.FileUtil$1.visitFile(FileUtil.java:137) ~[?:?]
	at net.pl3x.map.util.FileUtil$1.visitFile(FileUtil.java:128) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2724) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2796) ~[?:?]
	at net.pl3x.map.util.FileUtil.copyFromJar(FileUtil.java:128) ~[?:?]
	at net.pl3x.map.util.FileUtil.extractWebFolder(FileUtil.java:117) ~[?:?]
	at net.pl3x.map.Pl3xMap.start(Pl3xMap.java:49) ~[?:?]
	at net.pl3x.map.Pl3xMap.onEnable(Pl3xMap.java:36) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Purpur-936]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Purpur-936]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Purpur-936]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Purpur-936]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Purpur-936]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.4.jar:git-Purpur-936]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249) ~[patched_1.16.4.jar:git-Purpur-936]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:937) ~[patched_1.16.4.jar:git-Purpur-936]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Purpur-936]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[19:25:04] [Server thread/INFO]: [Pl3xMap] Disabling Pl3xMap v1.0
```

I've had this issue on my primary PC for quite some time now, but couldn't reproduce on a different windows VM.

The issue only occurs under Windows, but doesn't happen in Linux (ubuntu, specifically) nor WSL on the same windows installation.

I can "bypass" the issue by manually moving the web directory to the plugins directory and deleting the web folder from the jar which at least allows the plugin to start up (and remains fully functional).

Using Windows 10 x64 & Java 11.0.9 x64

**Comment by BillyGalbreath** [comment]
I hate windows so much

**Comment by BillyGalbreath** [comment]
As per conversation in Discord, it is caused by a bug in the JVM. Adopt fixed it in 11.0.9.1+1

**Comment by CocoTheOwner** [comment]
Good day, I downloaded the plugin and ran it, noticing the error that pointed to this issue report.
I updated my java version, only to find it doing the same thing.

Here is a snippet of my log (the very first lines) containing java information:
`java -Xms10G -Xmx10G -jar paper165.jar nogui
System Info: Java 11 (Java HotSpot(TM) 64-Bit Server VM 11.0.10+8-LTS-162) Host: Windows 10 10.0 (amd64)`

As you can see later in the log I am running the 124th BETA build on the latest 1.16.5 paper.

Full log: https://pastebin.com/y5mD7BtW

This is on a fresh 1.16.5 paper server (which I created after I ran it on a server with a bunch of other plugins to make sure it wasn't some kind of incompatibility).

Let me know if there's more information you need. I'd love to be able to use this software!

**Comment by DoctaEnkoda** [comment]
@CocoTheOwner Create an new issue pls

**Comment by BillyGalbreath** [comment]
Re-opening this as it seems newer JVM versions re-broke the same thing.

I'll have to find a different method to walking the file tree inside the jar for extracting the web folder to fix this for good.

**Comment by BillyGalbreath** [comment]
This has finally been fixed in build 135 \o/
