### ISSUE TITLE
mapSingleChunk failed

### ISSUE THREAD

**Issue by DoctaEnkoda** [pl3xgaming/Pl3xMap#68]
Hello I'm this error after big paste WorldEdit : 

Error Log
```
[14:54:47 WARN]: [net.pl3x.map.plugin.task.render.AbstractRender] mapSingleChunk failed!
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
at net.pl3x.map.plugin.data.BiomeColors.grassColorSampler(BiomeColors.java:166) ~[?:?]
at net.pl3x.map.plugin.data.BiomeColors.sampleNeighbors(BiomeColors.java:189) ~[?:?]
at net.pl3x.map.plugin.data.BiomeColors.grass(BiomeColors.java:160) ~[?:?]
at net.pl3x.map.plugin.data.BiomeColors.modifyColorFromBiome(BiomeColors.java:117) ~[?:?]
at net.pl3x.map.plugin.task.render.AbstractRender.getColor(AbstractRender.java:305) ~[?:?]
at net.pl3x.map.plugin.task.render.AbstractRender.scanBlock(AbstractRender.java:298) ~[?:?]
at net.pl3x.map.plugin.task.render.AbstractRender.scanChunk(AbstractRender.java:234) ~[?:?]
at net.pl3x.map.plugin.task.render.AbstractRender.lambda$mapSingleChunk$5(AbstractRender.java:201) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
... 3 more
```

##Plugins

```
Plugins (52): AuctionMaster, AuctionMasterItemDisplay, AutoRestart*, BanklandsGradle, BuycraftX, Chunky, Citizens, CitizensCMD, CMI, CMIEInjector*, CMILib, CrateReloaded, CrateReloadedNPC*, DiscordSRV, DynamicShop, EasyBackup, EasyBackupCore, HolographicDisplays, Hyperverse, Images, Insights, Jobs, JobsPlusEvolved, Lands, LandsDiscordBot, LiteBans, LocketteX, LuckPerms, MarriageMaster, MCRealistic-2, MinewebBridge, NoFurnace, OpenInv, Oraxen, Pl3xMap, Pl3xmap-WorldGuard, PlaceholderAPI, ProtocolLib, PunishGUI*, Quests, QuestsGUI, QuickShop, Rafk, Shopkeepers, SlotMachine, spark, TAB, TradePlus, Vault, ViewDistanceTweaks, WorldEdit, WorldGuard
```

##Versions Server
```
Checking version, please wait...
>.... [15:00:25 INFO]: This server is running Purpur version git-Purpur-"2721192" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2721192 on ver/1.17.1)
>.... [15:00:25 INFO]: You are 3 version(s) behind
```
I use custom build because i'm fix this crash issue : https://github.com/PaperMC/Paper/pull/6219

**Comment by DoctaEnkoda** [comment]
![image](https://user-images.githubusercontent.com/26461373/126194979-7e039c27-b02e-4930-8e89-4684fd05b7db.png)

**Comment by SirLeezus** [comment]
I'm having the same issue with build 162 using the Mojang lush caves datapack.

**Comment by Koudyasek** [comment]
I have same problem. Using Purpur 1.17.1, special world generator Iris
