### ISSUE TITLE
Map chunk column failed

### ISSUE THREAD

**Issue by MWHunter** [pl3xgaming/Pl3xMap#92]
[04:13:57] [pool-86-thread-1/WARN]: [net.pl3x.map.plugin.task.render.AbstractRender] mapChunkColumn failed!
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at net.pl3x.map.plugin.data.BiomeColors.grassColorSampler(BiomeColors.java:166) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
        at net.pl3x.map.plugin.data.BiomeColors.grass(BiomeColors.java:162) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
        at net.pl3x.map.plugin.data.BiomeColors.modifyColorFromBiome(BiomeColors.java:117) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
        at net.pl3x.map.plugin.task.render.AbstractRender.getColor(AbstractRender.java:305) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
        at net.pl3x.map.plugin.task.render.AbstractRender.scanBlock(AbstractRender.java:298) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
        at net.pl3x.map.plugin.task.render.AbstractRender.scanChunk(AbstractRender.java:234) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
        at net.pl3x.map.plugin.task.render.AbstractRender.lambda$mapChunkColumn$3(AbstractRender.java:176) ~[Pl3xMap-1.0.0-BETA-162.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
        ... 3 more

I am using the Terralith datapack and getting this error

**Comment by DoctaEnkoda** [comment]
Duplicate #68
