### ISSUE TITLE
Missing JSM permissions for path /

### ISSUE THREAD

**Issue by NeumimTo** [pl3xgaming/Pl3xMap#95]
Im hosting my server on a vps that has its own SecurityManager which appears to have problems with pl3xmap 

Any incoming request GET / results in exception

```
[01:19:29 ERROR]: [io.undertow.request] Missing JSM permissions for path /
java.lang.SecurityException: read permission error: /home/hosting
        at com.hicoria.javaSandBox.Main$CustomSecurityManager.checkRead(Main.java:427) ~[sdb:?]
        at sun.nio.fs.UnixPath.checkRead(UnixPath.java:810) ~[?:?]
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[?:?]
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
        at java.nio.file.Files.readAttributes(Files.java:1843) ~[?:?]
        at java.nio.file.Files.isSymbolicLink(Files.java:2269) ~[?:?]
        at io.undertow.server.handlers.resource.SecurityActions$1.run(SecurityActions.java:34) ~[?:?]
        at io.undertow.server.handlers.resource.SecurityActions$1.run(SecurityActions.java:31) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
        at io.undertow.server.handlers.resource.SecurityActions.isSymbolicLink(SecurityActions.java:31) ~[?:?]
        at io.undertow.server.handlers.resource.PathResourceManager.getSymlinkBase(PathResourceManager.java:315) ~[?:?]
        at io.undertow.server.handlers.resource.PathResourceManager.getResource(PathResourceManager.java:218) ~[?:?]
        at io.undertow.server.handlers.resource.DefaultResourceSupplier.getResource(DefaultResourceSupplier.java:39) ~[?:?]
        at io.undertow.server.handlers.resource.ResourceHandler$1.handleRequest(ResourceHandler.java:205) ~[?:?]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[?:?]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841) ~[?:?]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[?:?]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[?:?]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[?:?]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[01:19:29 ERROR]: [io.undertow.request] UT005071: Undertow request failed HttpServerExchange{ GET /}

**Comment by BillyGalbreath** [comment]
I'm not sure what this error is, or even how to fix it. I'm going to close this as "outside of scope" for the project since you mention you use your own SecurityManager, which suggests you know more than I do on the problem and how to fix or work around it.
