### ISSUE TITLE
Error on fullrender

### ISSUE THREAD

**Issue by Ghostaunt** [pl3xgaming/Pl3xMap#97]
When I sent command **/map fullrender world** got this error
```
[14:09:04] [Server thread/ERROR]: [Pl3xMap] An unhandled exception was thrown during command execution
net.pl3x.map.plugin.lib.cloud.commandframework.services.PipelineException: Failed to retrieve result from ServiceWrapper{type=net.pl3x.map.plugin.lib.cloud.commandframework.CommandManager$1@45b0b0e2,implementation=net.pl3x.map.plugin.lib.io.leangen.geantyref.TypeToken$1@9902f7ae}
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.ServiceSpigot.getResult(ServiceSpigot.java:98) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.CommandManager.preprocessContext(CommandManager.java:715) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.CommandManager.executeCommand(CommandManager.java:175) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:107) ~[Pl3xMap.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1395]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Purpur-1395]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:819) ~[patched_1.17.1.jar:git-Purpur-1395]
        at net.essentialsx.discord.interactions.commands.ExecuteCommand.lambda$onCommand$0(ExecuteCommand.java:26) ~[EssentialsXDiscord.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1395]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1395]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1395]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1395]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1395]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1395]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1395]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.pl3x.map.plugin.lib.cloud.commandframework.bukkit.internal.BukkitBackwardsBrigadierSenderMapper.apply(BukkitBackwardsBrigadierSenderMapper.java:57) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.brigadier.CloudBrigadierManager.lambda$new$1(CloudBrigadierManager.java:133) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.types.ConsumerService.handle(ConsumerService.java:57) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.types.ConsumerService.handle(ConsumerService.java:39) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.ServiceSpigot.getResult(ServiceSpigot.java:95) ~[Pl3xMap.jar:?]
        ... 15 more
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.bukkit.internal.BukkitBackwardsBrigadierSenderMapper.apply(BukkitBackwardsBrigadierSenderMapper.java:55) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.brigadier.CloudBrigadierManager.lambda$new$1(CloudBrigadierManager.java:133) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.types.ConsumerService.handle(ConsumerService.java:57) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.types.ConsumerService.handle(ConsumerService.java:39) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.ServiceSpigot.getResult(ServiceSpigot.java:95) ~[Pl3xMap.jar:?]
        ... 15 more
Caused by: java.lang.IllegalArgumentException: Cannot make net.ess3.provider.providers.PaperCommandSender@48182b9d a vanilla command listener
        at org.bukkit.craftbukkit.v1_17_R1.command.VanillaCommandWrapper.getListener(VanillaCommandWrapper.java:86) ~[patched_1.17.1.jar:git-Purpur-1395]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.bukkit.internal.BukkitBackwardsBrigadierSenderMapper.apply(BukkitBackwardsBrigadierSenderMapper.java:55) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.brigadier.CloudBrigadierManager.lambda$new$1(CloudBrigadierManager.java:133) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.types.ConsumerService.handle(ConsumerService.java:57) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.types.ConsumerService.handle(ConsumerService.java:39) ~[Pl3xMap.jar:?]
        at net.pl3x.map.plugin.lib.cloud.commandframework.services.ServiceSpigot.getResult(ServiceSpigot.java:95) ~[Pl3xMap.jar:?]
        ... 15 more```

**Comment by Ghostaunt** [comment]
It shown only that in log file 
![image](https://user-images.githubusercontent.com/798011/136508620-b7f9308f-a15c-40c5-9a85-960fd0300220.png)

**Comment by BillyGalbreath** [comment]
This is an error from the Cloud command library we use. The library, sadly, is very sensitive to a few things in the server. Be sure you are using the most up to date version for the server you are using, and make sure your server is not too far down the fork tree. We only officially support Paper, Airplane, and Purpur.
